### ISSUE TITLE
Rates are not consistent

### ISSUE THREAD

**Issue by dirkam** [fixerAPI/fixer#10]
I'd like to get HUF/EUR rates.

http://api.fixer.io/latest?base=HUF returns 0.0032 for EUR (1 EUR = 318.75 HUF).
http://api.fixer.io/latest returns 314.7 (1 EUR = 314.7 HUF)

And the former does not seem to change, when the latter does.

Can you please check it? Thanks.

**Comment by hakanensari** [comment]
We must be rounding off too aggressively [here](https://github.com/hakanensari/fixer-io/blob/master/lib/quote.rb#L51).

I originally chose to round off up to four places because that's what the original dataset seems to do. I'll see if I can revise this to make it work better for currencies like HUF.
