### ISSUE TITLE
Exchange rates for a period of time

### ISSUE THREAD

**Issue by trofim24** [fixerAPI/fixer#22]
Hey. Is it possible to add the ability to receive exchange rates for a period of time.
For example, get the data for the last month. Not very convenient to do about 30 requests for this

**Comment by jiayihu** [comment]
Would be a very nice feature. I'm currently making a side-project with charts and this feature would be very helpful.

**Comment by hakanensari** [comment]
Sounds good.

Following the API of the historical query, we'd want something like:

``` HTTP
GET /:start/:end
```

... where **start** and **end** are in `yyyy-mm-dd` format, plus **base** and **symbols** as optional parameters. Invalid dates and base should throw errors.

I'm happy to accept a PR for this. Otherwise, I'll take a stab myself some time in the near future.

**Comment by levipadre** [comment]
This feature would be really great and useful

**Comment by Dooza** [comment]
Agreed, I think it would be useful for feeding JSON to a graph to display a range of data.

**Comment by rafaell-lycan** [comment]
+1 👍

**Comment by malafeev** [comment]
+1 👍

**Comment by dani3l** [comment]
+1 :+1:

**Comment by ryanwalters** [comment]
+1

**Comment by wildest** [comment]
+1
This would also be helpful if it returned the aggregated average of the daily rates for the same period.

**Comment by valeIT** [comment]
+1 

Any progress on this?

**Comment by Sweeper777** [comment]
+1

**Comment by ma1onso** [comment]
Waiting for this, I'm Python developer sorry :(

**Comment by platoniusen** [comment]
+1
