### ISSUE TITLE
<= date fetch logic can produce confusing results

### ISSUE THREAD

**Issue by gregl83** [fixerAPI/fixer#89]
I realize this would be a major breaking change; however, reading through the documentation it wasn't clear to me that when providing a date (today before 4pm CET or future date) the API would return the last successfully saved rate and date.

**For example:**
Using date param value [2057-12-13](https://api.fixer.io/2057-12-13?base=USD) returns the LATEST values available and the date they were recorded. That seems like a nice feature instead of a 400; however, with currency applications it can have unexpected results. IMO it's better to not infer or save bad requests from failure.

**Weekend example:**
If the request is made for rates on a Sunday (non-trading day) the results will return the values of equal to the date of Sunday or the previous most recent saved values.
So using date param value [2017-12-10](https://api.fixer.io/2017-12-10?base=USD) (Sunday) returns the date of 2017-12-08 (Friday).

**Lastly:**
When requesting rates for today, prior to 4pm CET (UTC in docs could be helpful) or the rates being persisted, the returned rates will be for yesterday or if request on a Monday for Friday.

The result could lead to some use-cases requiring extra logic to determine if the returned rates date matches the request date or purely overlooked when caching the values. Indexing the rates on the returned date also requires application logic to apply the same set of rules.

**Comment by hakanensari** [comment]
I see your points, but it would not be a good idea to change the logic so drastically after this API has been in production for so long. The one thing I could do is put a guard against future dates (honestly, I never thought of that edge case). But I suppose that's a minor point.

Some more thoughts —

You could argue `latest` is not ambiguous: it promises the _latest_ available date, which is not necessarily the current date. The [`Last-Modified` header](https://github.com/hakanensari/fixer/blob/master/app/lib/api.rb#L59) should help here with caching.

I do agree the historical queries are a bit ambiguous, and we could further clarify this in the README. If I remember correctly, my call to return the latest available date rather than `404`s for holidays had to do with convenience. I was converting values of past transactions in my e-commerce app ("What was the USD value of this order on the date it sold?") and preferred the API to handle the extra logic of figuring out the last working day for weekends and other holidays.

If you require precise days when querying history, you will have to implement a guard on the client side to ignore/discard if returned date is not the date you queried. If you do require a value for holidays, then the ECB dataset is not good for you.
